name: Checkov Analysis
description: Run Checkov scans for Terraform code
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'

    - name: Install pip
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip

    - name: Install Checkov
      run: |
        pip install checkov

    - name: Run Checkov (skip specific checks)
      run: checkov -d terraform/env --skip-check CKV2_AWS_5,CKV2_AWS_12,CKV2_AWS_64
